name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: RyuuYZ
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2338bdf8&color_dots=%230f172a,%230c4a6e,%230369a1,%230ea5e9,%2338bdf8
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2338bdf8&color_dots=%230f172a,%230c4a6e,%230369a1,%230ea5e9,%2338bdf8

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}